const topics = [
  {
    id: 'home',
    title: 'Home',
    icon: '🏠',
    file: 'README.md',
    description: 'Overview & Study Guide',
    problems: '2,700+',
    categories: '225+',
  },
  {
    id: 'arrays',
    title: 'Arrays',
    icon: '📊',
    file: 'arrays.md',
    description: 'Two pointers, sliding window, prefix sum, and more',
    problems: '400+',
    categories: '28',
  },
  {
    id: 'binary-search',
    title: 'Binary Search',
    icon: '🔍',
    file: 'binary_search.md',
    description: 'BS on answer, Kth element, matrix search',
    problems: '250+',
    categories: '25',
  },
  {
    id: 'dynamic-programming',
    title: 'Dynamic Programming',
    icon: '🧩',
    file: 'dynamic_programming.md',
    description: 'Linear DP, bitmask, digit DP, game theory',
    problems: '300+',
    categories: '22',
  },
  {
    id: 'graphs',
    title: 'Graphs',
    icon: '🕸️',
    file: 'graphs.md',
    description: 'BFS, DFS, Dijkstra, Union-Find, MST, SCC',
    problems: '300+',
    categories: '30',
  },
  {
    id: 'greedy',
    title: 'Greedy Algorithms',
    icon: '🎯',
    file: 'greedy.md',
    description: 'Exchange argument, interval scheduling, regret-based',
    problems: '350+',
    categories: '25',
  },
  {
    id: 'priority-queue',
    title: 'Priority Queue / Heap',
    icon: '⛰️',
    file: 'priority_queue.md',
    description: 'Top-K, two heaps, Dijkstra, k-way merge',
    problems: '280+',
    categories: '25',
  },
  {
    id: 'stack-queue',
    title: 'Stack & Queue',
    icon: '📚',
    file: 'stack_queue.md',
    description: 'Monotonic stack, expression eval, BFS, deque',
    problems: '300+',
    categories: '25',
  },
  {
    id: 'trees',
    title: 'Trees',
    icon: '🌳',
    file: 'trees.md',
    description: 'Binary trees, BST, traversals, construction',
    problems: '300+',
    categories: '25',
  },
  {
    id: 'tries',
    title: 'Trie (Prefix Tree)',
    icon: '🔤',
    file: 'tries.md',
    description: 'Bitwise trie, Aho-Corasick, autocomplete',
    problems: '200+',
    categories: '20',
  },
  {
    id: 'two-pointers',
    title: 'Two Pointers & Sliding Window',
    icon: '👆',
    file: 'two_pointers_sliding_window.md',
    description: 'Opposite/same direction, fixed/variable window',
    problems: '350+',
    categories: '25',
  },
]

export default topics
